P:
  request_rate: 5  # число запросов в единицу времени (поток заявок)
  simulation_time: 100  # общее время симуляции
  read_probability: 0.5  # вероятность, что запрос будет на чтение

Q:
  response_timeout: 100.0 # максимальное время ожидания ответа от нижестоящих сервисов

T:
  read_failure_probability: 0 # вероятность отказа сервиса при чтении
  write_failure_probability: 0 # вероятность отказа сервиса при записи

S:
  read_failure_probability: 0 # вероятность отказа сервиса при чтении
  write_failure_probability: 0 # вероятность отказа сервиса при записи
  max_write_time: 1.0 # максимальное время записи
  max_read_time: 0.5 # максимальное время чтения
  concurrency_limit: 3 # максимальное количество одновременно выполняемых операций
