P:
  arrival_process: fixed_interval # "poisson" или "fixed_interval"
  mean_interarrival: 0.2          # для "poisson" поток с интенсивностью ~5 req/ед.времени
  read_probability: 0.5           # вероятность, что запрос будет на чтение
  num_requests: 50                # всего обработать 50 запросов
  num_users: 5                    # кол-во параллельных пользователей 

Q:
  response_timeout: 100.0 # максимальное время ожидания ответа от нижестоящих сервисов

T:
  read_failure_probability: 0 # вероятность отказа сервиса при чтении
  write_failure_probability: 0 # вероятность отказа сервиса при записи

S:
  read_failure_probability: 0 # вероятность отказа сервиса при чтении
  write_failure_probability: 0 # вероятность отказа сервиса при записи
  max_write_time: 1.0 # максимальное время записи
  max_read_time: 0.5 # максимальное время чтения
  concurrency_limit: 3 # максимальное количество одновременно выполняемых операций
